### ISSUE TITLE
Error from Busola container: unable to verify the first certificate

### ISSUE THREAD

**Issue by shorim** [kyma-project/busola#564]
**Description**
After you run `busola` using `docker run --rm -it -p 3001:3001 -e DOCKER_DESKTOP_CLUSTER=true --pid=host --name busola eu.gcr.io/kyma-project/busola:latest` and then add a cluster, the following error is logged from the container:
```sh
{"level":40,"time":1636998342934,"pid":41281,"hostname":"8ddc6920cd16","req":{"id":"68437d7f-b9f6-457e-b56e-0de901d49eea","method":"GET","url":"/backend/api","cluster_url":"https://api.mostafa.berlin.shoot.canary.k8s-hana.ondemand.com"},"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE","stack":"Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket._finishInit (_tls_wrap.js:937:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)","type":"Error","msg":"unable to verify the first certificate"}
```

Also note that consequently this error also occurs when you run the `dashboard` command from `Kyma CLI`:
```sh
./bin/kyma-darwin dashboard          
| Starting container: busola: latest: Pulling from kyma-project/busola
Digest: sha256:1aae8dce97cb7851c8e30abc77250e6d3c50562231dd33cb0addffc5a720f574
Status: Image is up to date for eu.gcr.io/kyma-project/busola:latest
- Started container: busola
- Opening the Kyma dashboard in the default browser using the following url: http://localhost:3001?kubeconfigID=config.yaml
Busola backend server started @ 3001!
{"level":40,"time":1636994800155,"pid":1,"hostname":"3948a88242ea","req":{"id":"4ce4c888-6344-4a13-9a97-762d8dbc8a97","method":"GET","url":"/backend/api","cluster_url":"https://0.0.0.0:60832"},"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE","stack":"Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket._finishInit (_tls_wrap.js:937:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)","type":"Error","msg":"unable to verify the first certificate"}
```

**Expected result**
The `busola` container doesn't log any errors.

**Actual result**
The `busola` container log the following error:
```sh
{"level":40,"time":1636994800155,"pid":1,"hostname":"3948a88242ea","req":{"id":"4ce4c888-6344-4a13-9a97-762d8dbc8a97","method":"GET","url":"/backend/api","cluster_url":"https://0.0.0.0:60832"},"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE","stack":"Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket._finishInit (_tls_wrap.js:937:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)","type":"Error","msg":"unable to verify the first certificate"}
```

**Steps to reproduce**

1. Run busola container: `docker run --rm -it -p 3001:3001 -e DOCKER_DESKTOP_CLUSTER=true --pid=host --name busola eu.gcr.io/kyma-project/busola:latest`
2. Add a cluster
3. The container logs the error mentioned above.

**Comment by Wawrzyn321** [comment]
Hi! This is caused by the call performed when we first connect to a cluster in Busola. We can't avoid it, so instead we made it error less frequently - it will error only if you use a "kubeconfig for Kyma 1.x cluster downloaded from Console". If you're interested in technical details ping me here, I'll add my PR.
